# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generatelonglivetokenform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .fbpy_graph_api import *


class Ui_GenerateLongLiveTokenForm(object):
    def setupUi(self, GenerateLongLiveTokenForm):
        GenerateLongLiveTokenForm.setObjectName("GenerateLongLiveTokenForm")
        GenerateLongLiveTokenForm.resize(372, 241)
        self.horizontalLayoutWidget = QtWidgets.QWidget(GenerateLongLiveTokenForm)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 251, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_id_title_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.app_id_title_label.setFont(font)
        self.app_id_title_label.setObjectName("app_id_title_label")
        self.horizontalLayout.addWidget(self.app_id_title_label)
        self.app_id_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.app_id_lineEdit.setObjectName("app_id_lineEdit")
        self.horizontalLayout.addWidget(self.app_id_lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(GenerateLongLiveTokenForm)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 281, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.app_secret_title_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.app_secret_title_label.setFont(font)
        self.app_secret_title_label.setObjectName("app_secret_title_label")
        self.horizontalLayout_2.addWidget(self.app_secret_title_label)
        self.app_secret_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.app_secret_lineEdit.setObjectName("app_secret_lineEdit")
        self.horizontalLayout_2.addWidget(self.app_secret_lineEdit)
        self.long_live_token_TextEdit = QtWidgets.QTextEdit(GenerateLongLiveTokenForm)
        self.long_live_token_TextEdit.setGeometry(QtCore.QRect(40, 110, 311, 81))
        self.long_live_token_TextEdit.setReadOnly(True)
        self.long_live_token_TextEdit.setObjectName("long_live_token_TextEdit")
        self.long_live_token_gen_button = QtWidgets.QPushButton(GenerateLongLiveTokenForm)
        self.long_live_token_gen_button.setGeometry(QtCore.QRect(100, 200, 75, 23))
        self.long_live_token_gen_button.setObjectName("long_live_token_gen_button")
        self.long_live_token_close_button = QtWidgets.QPushButton(GenerateLongLiveTokenForm)
        self.long_live_token_close_button.setGeometry(QtCore.QRect(190, 200, 75, 23))
        self.long_live_token_close_button.setObjectName("long_live_token_close_button")

        self.retranslateUi(GenerateLongLiveTokenForm)
        QtCore.QMetaObject.connectSlotsByName(GenerateLongLiveTokenForm)

    def retranslateUi(self, GenerateLongLiveTokenForm):
        _translate = QtCore.QCoreApplication.translate
        GenerateLongLiveTokenForm.setWindowTitle(_translate("GenerateLongLiveTokenForm", "長期 ACCESS_TOKEN "))
        self.app_id_title_label.setText(_translate("GenerateLongLiveTokenForm", "APP ID"))
        self.app_secret_title_label.setText(_translate("GenerateLongLiveTokenForm", "APP SECRET"))
        self.long_live_token_gen_button.setText(_translate("GenerateLongLiveTokenForm", "產生"))
        self.long_live_token_close_button.setText(_translate("GenerateLongLiveTokenForm", "關閉"))

class GenerateLongLiveTokenForm(QtWidgets.QDialog, Ui_GenerateLongLiveTokenForm):
    def __init__(self, parent=None):
        super(GenerateLongLiveTokenForm, self).__init__(parent)
        self.setupUi(self)

        self.long_live_token_gen_button.clicked.connect(self.longlivetoken_generate)
        self.long_live_token_close_button.clicked.connect(self.longlivetoken_save_and_close)
        self.longlivetoken_gen_check_msg = "APP ID 或 APP SECRET 不能為空"
        self.longlivetoken_gen_msg = "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ff0000;\">APP ID 或 APP SECRET 不能為空</body></html>"
    
    def longlivetoken_generate(self):
        if self.app_id_lineEdit.text() and self.app_secret_lineEdit.text():
            try:
                response = get_long_lived_token(app_id=self.app_id_lineEdit.text(), app_secret=self.app_secret_lineEdit.text())
            except FacebookError as e:
                logger.error(f"Error occurred while interacting with Facebook: {e}")
        else:
            self.long_live_token_TextEdit.setHtml(self.longlivetoken_gen_msg)
        
    def longlivetoken_save_and_close(self):
        # 在這裡，您可以添加保存設置的代碼。
        self.close()
