# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from pyqt_switch import PyQtSwitch
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.post_plainText_edit = QtWidgets.QPlainTextEdit(self.tab)
        self.post_plainText_edit.setGeometry(QtCore.QRect(40, 50, 341, 401))
        self.post_plainText_edit.setCenterOnScroll(True)
        self.post_plainText_edit.setObjectName("post_plainText_edit")
        self.file_path_label = QtWidgets.QLabel(self.tab)
        self.file_path_label.setGeometry(QtCore.QRect(400, 20, 61, 20))
        self.file_path_label.setObjectName("file_path_label")
        self.image_path_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.image_path_lineEdit.setGeometry(QtCore.QRect(460, 20, 241, 21))
        self.image_path_lineEdit.setInputMask("")
        self.image_path_lineEdit.setReadOnly(True)
        self.image_path_lineEdit.setObjectName("image_path_lineEdit")
        self.upload_image_button = QtWidgets.QPushButton(self.tab)
        self.upload_image_button.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.upload_image_button.setObjectName("upload_image_button")
        self.image_preview_label = QtWidgets.QLabel(self.tab)
        self.image_preview_label.setGeometry(QtCore.QRect(400, 50, 381, 401))
        font = QtGui.QFont()
        font.setBold(True)
        self.image_preview_label.setFont(font)
        self.image_preview_label.setStyleSheet("border :1.5px black;\n"
"border-style : dashed;")
        self.image_preview_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_preview_label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_preview_label.setObjectName("image_preview_label")
        self.execution_log_TextEdit = QtWidgets.QTextEdit(self.tab)
        self.execution_log_TextEdit.setEnabled(True)
        self.execution_log_TextEdit.setGeometry(QtCore.QRect(40, 480, 581, 91))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.execution_log_TextEdit.setFont(font)
        self.execution_log_TextEdit.setStyleSheet("background-color: black; color: white;")
        self.execution_log_TextEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.execution_log_TextEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.execution_log_TextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.execution_log_TextEdit.setUndoRedoEnabled(True)
        self.execution_log_TextEdit.setReadOnly(True)
        self.execution_log_TextEdit.setObjectName("execution_log_TextEdit")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(640, 480, 160, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.reset_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout_1.addWidget(self.reset_button)
        self.post_setting_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.post_setting_button.setObjectName("post_setting_button")
        self.verticalLayout_1.addWidget(self.post_setting_button)
        self.publish_post_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.publish_post_button.setObjectName("publish_post_button")
        self.verticalLayout_1.addWidget(self.publish_post_button)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.access_token_label = QtWidgets.QLabel(self.tab_2)
        self.access_token_label.setGeometry(QtCore.QRect(30, 80, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.access_token_label.setFont(font)
        self.access_token_label.setObjectName("access_token_label")
        self.token_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.token_textEdit.setEnabled(True)
        self.token_textEdit.setGeometry(QtCore.QRect(30, 100, 261, 121))
        self.token_textEdit.setPlaceholderText("")
        self.token_textEdit.setObjectName("token_textEdit")
        self.switch_state_label = QtWidgets.QLabel(self.tab_2)
        self.switch_state_label.setGeometry(QtCore.QRect(140, 20, 53, 15))
        font = QtGui.QFont()
        font.setBold(True)
        self.switch_state_label.setFont(font)
        self.switch_state_label.setObjectName("switch_state_label")

        #
        self.switch_button = PyQtSwitch()
        self.switch_button.setParent(self.tab_2)
        self.switch_button.setObjectName("switch_button")
        self.switch_button.setGeometry(QtCore.QRect(80, 18, 60, 30))  # 請根據需要調整位置和大小
        self.switch_button.setAnimation(True)
        self.switch_button.toggled.connect(self.on_switch_toggle)
        #
        MainWindow.setWindowIcon(QtGui.QIcon('../img/channels4_profile.ico'))

        self.warning_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.warning_textEdit.setEnabled(True)
        self.warning_textEdit.setGeometry(QtCore.QRect(310, 160, 261, 51))
        self.warning_textEdit.setStyleSheet("color:rgba(255, 0, 0, 255);")
        self.warning_textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.warning_textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.warning_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.warning_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.warning_textEdit.setReadOnly(True)
        self.warning_textEdit.setObjectName("warning_textEdit")
        self.long_live_token_button = QtWidgets.QPushButton(self.tab_2)
        self.long_live_token_button.setGeometry(QtCore.QRect(310, 130, 251, 23))
        self.long_live_token_button.setObjectName("long_live_token_button")
        self.api_label = QtWidgets.QLabel(self.tab_2)
        self.api_label.setGeometry(QtCore.QRect(30, 50, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.api_label.setFont(font)
        self.api_label.setObjectName("api_label")
        self.api_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.api_LineEdit.setGeometry(QtCore.QRect(120, 50, 41, 21))
        self.api_LineEdit.setText("")
        self.api_LineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.api_LineEdit.setObjectName("api_LineEdit")
        self.switch_label = QtWidgets.QLabel(self.tab_2)
        self.switch_label.setGeometry(QtCore.QRect(30, 20, 53, 15))
        font = QtGui.QFont()
        font.setBold(True)
        self.switch_label.setFont(font)
        self.switch_label.setObjectName("switch_label")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "粉專即時推播器 @MUSE"))
        self.post_plainText_edit.setPlaceholderText(_translate("MainWindow", "請輸入欲發送之貼文內容"))
        self.file_path_label.setText(_translate("MainWindow", "檔案路徑："))
        self.upload_image_button.setText(_translate("MainWindow", "選擇圖片"))
        self.image_preview_label.setText(_translate("MainWindow", "預覽圖片(可拖曳至此)"))
        self.execution_log_TextEdit.setPlaceholderText(_translate("MainWindow", "執行紀錄："))
        self.reset_button.setText(_translate("MainWindow", "恢復預設"))
        self.post_setting_button.setText(_translate("MainWindow", "發文對象"))
        self.publish_post_button.setText(_translate("MainWindow", "發布貼文"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.access_token_label.setText(_translate("MainWindow", "USER ACCESS TOKEN："))
        self.switch_state_label.setText(_translate("MainWindow", "ON"))
        self.warning_textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft JhengHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">短期 ACCESS_TOKEN 有時效性，<br />或是更換長期 ACCESS_TOKEN，<br />保存於本地端有洩漏ACCESS_TOKEN的風險。</span></p></body></html>"))
        self.long_live_token_button.setText(_translate("MainWindow", "產生長期 ACCESS TOKEN(Comming Soon)"))
        self.api_label.setText(_translate("MainWindow", "API Version："))
        self.switch_label.setText(_translate("MainWindow", "Switch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "設置"))

    def on_switch_toggle(self, checked):
        if checked:
            self.token_textEdit.setReadOnly(True)  # Lock the token_textEdit
            self.api_LineEdit.setReadOnly(True)
            self.api_LineEdit.setStyleSheet("background-color: rgba(255, 255, 225, 127);")  # Set semi-transparent gray background
            self.token_textEdit.setStyleSheet("background-color: rgba(255, 255, 225, 127);")  # Set semi-transparent gray background
            self.switch_state_label.setText("ON")
        else:
            self.token_textEdit.setReadOnly(False)  # Unlock the token_textEdit
            self.api_LineEdit.setReadOnly(False)
            self.token_textEdit.setStyleSheet("")  # Reset the style
            self.api_LineEdit.setStyleSheet("")  # Reset the style
            self.switch_state_label.setText("OFF")

    def reset_ui(self):
        # 清空PlainTextEdit
        self.post_plainText_edit.clear()
        # 清空Label for 預覽圖片
        self.image_preview_label.clear()
        self.image_preview_label.setText("預覽圖片(可拖曳至此)")
        # 清空檔案路徑LineEdit
        self.image_path_lineEdit.clear()
        # 清空執行紀錄TextEdit
        self.execution_log_TextEdit.clear()